#!/bin/bash
# Call the script using the command: Cpuniq directoryname

####################################################################################################################################
# Script to finalize conformer uniqueness filtering after 'duplicates' script has been run.
# For every conformer listed in Unique.txt, copy the xyz file into the new directory specified in the input.
# With all unique conformer xyzs in the new directory, you may easily run the 'NextLevelInput' script to generate a set of input files.
#####################################################################################################################################

mkdir $1

sed -i '1d' Unique.txt   # Delete the title line from the file.

while [ -s Unique.txt ]
do
f=$(head -1 Unique.txt | awk '{print $1}')
cp $f.xyz $1
#mv $f.* $1              # Uncomment this option to move all conformer-specific files to the new directory.
sed -i '1d' Unique.txt   # Delete line from Unique.txt
done

rm Unique.txt
